// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNYMhm9-_Nc0FnzfjeG-GXkAjFwwmSoSU',
    appId: '1:835145143710:web:1068df35ab7c7f56d2328f',
    messagingSenderId: '835145143710',
    projectId: 'fir-authentication-act13',
    authDomain: 'fir-authentication-act13.firebaseapp.com',
    storageBucket: 'fir-authentication-act13.firebasestorage.app',
    measurementId: 'G-3TNVC1E5MY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw7AZLP212yuokO9XFm2thqjLcFJiS8bw',
    appId: '1:835145143710:android:3c54c20b2171f10cd2328f',
    messagingSenderId: '835145143710',
    projectId: 'fir-authentication-act13',
    storageBucket: 'fir-authentication-act13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqBY_FCkellOYGfF7Jq0nVnaXqxN_dczQ',
    appId: '1:835145143710:ios:3862b9c2803eae2cd2328f',
    messagingSenderId: '835145143710',
    projectId: 'fir-authentication-act13',
    storageBucket: 'fir-authentication-act13.firebasestorage.app',
    iosBundleId: 'com.example.act13AuthenticationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqBY_FCkellOYGfF7Jq0nVnaXqxN_dczQ',
    appId: '1:835145143710:ios:3862b9c2803eae2cd2328f',
    messagingSenderId: '835145143710',
    projectId: 'fir-authentication-act13',
    storageBucket: 'fir-authentication-act13.firebasestorage.app',
    iosBundleId: 'com.example.act13AuthenticationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNYMhm9-_Nc0FnzfjeG-GXkAjFwwmSoSU',
    appId: '1:835145143710:web:0fb14e0e02f25a59d2328f',
    messagingSenderId: '835145143710',
    projectId: 'fir-authentication-act13',
    authDomain: 'fir-authentication-act13.firebaseapp.com',
    storageBucket: 'fir-authentication-act13.firebasestorage.app',
    measurementId: 'G-7KW4QHDQ4E',
  );
}
